import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundImage: "url('/background.jpg')", // Chemin vers ton image dans le dossier public
          backgroundSize: "cover", // L'image couvre toute la surface
          backgroundPosition: "center", // L'image est centrée
          backgroundRepeat: "no-repeat", // Pas de répétition
          minHeight: "100vh", // S'assure que la hauteur minimale est celle de l'écran
        }}
      >
        {children}
      </body>
    </html>
  );
}
